name:                call-alloy
version:             0.2.0.0
github:              "marcellussiegburg/call-alloy"
license:             MIT
author:              "Marcellus Siegburg"
maintainer:          "marcellus.siegburg@uni-due.de"
copyright:           "2019 Marcellus Siegburg"

extra-source-files:
- README.md
- LICENSE
- ChangeLog.md
- bin/alloy/RunAlloy.class
- bin/org.alloytools.alloy.dist.jar

synopsis:            A simple library to call Alloy given a specification
category:            Language

description:         Please see the README on GitHub at <https://github.com/marcellussiegburg/call-alloy#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- file-embed
- filepath
- hashable
- lens
- mtl
- process
- split
- trifecta
when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src
  exposed-modules:
    - Language.Alloy.Call

tests:
  call-alloy-test:
    main:                Spec.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - call-alloy
    - hspec
