name:                call-alloy
version:             0.2.1.0
github:              "marcellussiegburg/call-alloy"
license:             MIT
author:              "Marcellus Siegburg"
maintainer:          "marcellus.siegburg@uni-due.de"
copyright:           "2019-2020 Marcellus Siegburg"

extra-source-files:
- README.md
- LICENSE
- ChangeLog.md
- bin/alloy/RunAlloy.class
- bin/org.alloytools.alloy.dist.jar
- bin/commons-cli/commons-cli-1.4.jar
- bin/commons-cli/NOTICE.txt
- bin/commons-cli/LICENSE.txt

synopsis:            A simple library to call Alloy given a specification
category:            Language

description:         Please see the README on GitHub at <https://github.com/marcellussiegburg/call-alloy#readme>

dependencies:
- base                        >= 4.7 && < 5
- bytestring                  >= 0.10 && < 0.12
- containers                  >= 0.6 && < 0.7
- directory                   >= 1.3 && < 1.4
- filepath                    >= 1.4 && < 1.5
- file-embed                  >= 0.0.11 && < 0.1
- hashable                    >= 1.2 && < 1.4
- lens                        >= 4.17 && < 4.20
- mtl                         >= 2.2 && < 2.3
- process                     >= 1.6 && < 1.7
- split                       >= 0.2 && < 0.3
- trifecta                    >= 2 && < 2.2
when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32                   >= 2.5 && < 2.11
  else:
    dependencies:
    - unix                    >= 2.7 && < 2.8

library:
  source-dirs: src
  exposed-modules:
    - Language.Alloy.Call

tests:
  call-alloy-test:
    main:                Spec.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - call-alloy
    - hspec
